export interface ServiceAreaRegion {
  region: string;
  suburbs: string[];
}

export const SYDNEY_SERVICE_AREAS: ServiceAreaRegion[] = [
  {
    region: 'Sydney CBD & Inner City',
    suburbs: [
      'Sydney CBD',
      'The Rocks',
      'Circular Quay',
      'Darlinghurst',
      'Surry Hills',
      'Redfern',
      'Pyrmont',
      'Ultimo',
      'Chippendale',
      'Haymarket',
      'Barangaroo',
    ],
  },
  {
    region: 'Eastern Suburbs',
    suburbs: [
      'Bondi',
      'Bondi Beach',
      'Bondi Junction',
      'Bronte',
      'Coogee',
      'Clovelly',
      'Randwick',
      'Kensington',
      'Maroubra',
      'Paddington',
      'Woollahra',
      'Double Bay',
      'Rose Bay',
      'Vaucluse',
      'Dover Heights',
      'Waverley',
    ],
  },
  {
    region: 'Northern Beaches',
    suburbs: [
      'Manly',
      'Dee Why',
      'Freshwater',
      'Curl Curl',
      'Narrabeen',
      'Mona Vale',
      'Newport',
      'Avalon',
      'Palm Beach',
      'Collaroy',
      'Brookvale',
      'Warriewood',
      'Balgowlah',
      'Fairlight',
    ],
  },
  {
    region: 'North Shore',
    suburbs: [
      'Chatswood',
      'North Sydney',
      'Crows Nest',
      'Neutral Bay',
      'Mosman',
      'Cremorne',
      'St Leonards',
      'Artarmon',
      'Lane Cove',
      'Willoughby',
      'Lindfield',
      'Roseville',
      'Killara',
      'Gordon',
      'Pymble',
      'Turramurra',
      'Hornsby',
    ],
  },
  {
    region: 'Inner West',
    suburbs: [
      'Newtown',
      'Glebe',
      'Annandale',
      'Leichhardt',
      'Balmain',
      'Rozelle',
      'Lilyfield',
      'Haberfield',
      'Marrickville',
      'Dulwich Hill',
      'Petersham',
      'Stanmore',
      'Enmore',
      'Ashfield',
      'Summer Hill',
      'Lewisham',
    ],
  },
  {
    region: 'Western Sydney',
    suburbs: [
      'Parramatta',
      'Westmead',
      'Blacktown',
      'Penrith',
      'Liverpool',
      'Campbelltown',
      'Bankstown',
      'Auburn',
      'Granville',
      'Merrylands',
      'Fairfield',
      'Cabramatta',
      'Wetherill Park',
      'Mount Druitt',
      'St Marys',
      'Ingleburn',
    ],
  },
  {
    region: 'Hills District',
    suburbs: [
      'Castle Hill',
      'Baulkham Hills',
      'Kellyville',
      'Rouse Hill',
      'Bella Vista',
      'Norwest',
      'West Pennant Hills',
      'Cherrybrook',
      'Dural',
      'Annangrove',
      'Glenhaven',
      'Castle Cove',
    ],
  },
  {
    region: 'South Sydney',
    suburbs: [
      'Hurstville',
      'Kogarah',
      'Rockdale',
      'Brighton-Le-Sands',
      'Arncliffe',
      'Banksia',
      'Wolli Creek',
      'Sutherland',
      'Cronulla',
      'Miranda',
      'Caringbah',
      'Gymea',
      'Engadine',
      'Menai',
      'Bangor',
    ],
  },
];

